name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Quarto
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb
          rm quarto-linux-amd64.deb
          quarto --version

      - name: Render site
        run: |
          quarto render
          # 添加必要的文件
          touch docs/.nojekyll
          echo "Your custom domain" > docs/CNAME

      # 不需要单独的部署步骤，GitHub 会自动部署 docs 文件夹