name: Deploy to GitHub Pages
on:
  workflow_dispatch:  # 允许手动触发
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'shusuh-pop'
          git config --global user.email '982924077@qq.com'
          git push origin --force gh-pages
